version: "3.8"
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - ${HOST_DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    networks:
      - lesson
networks:
  lesson: